### ISSUE TITLE
Z homing moves 10mm up

### ISSUE THREAD

**Issue by szerwi** [SkyNet3D/Marlin#10]
Hi,

When I'm doing home axis the Z axis is homing, but then it's moving 10mm up. How to disable it? I want to have it on the position that it will be printing to correctly level the bed.

**Comment by oderwat** [comment]
http://marlinfw.org/docs/configuration/configuration.html#probe-clearance

**Comment by szerwi** [comment]
So I should change #define Z_CLEARANCE_DEPLOY_PROBE from 10 to 0?

**Comment by szerwi** [comment]
Don't know how to do it... :/ Is the print starting at 0.3mm Z height? How to set it?

**Comment by szerwi** [comment]
Ok, I've done that. One more question. Is there an option to change fan cooling from 0-255 scale to percentage scale in options?
