### ISSUE TITLE
When compiling with unified bed leveling compile fails

### ISSUE THREAD

**Issue by TheWalterWhite** [SkyNet3D/Marlin#12]
If I switch to AUTO_BED_LEVELING_UBL the program fails to compile with the error `Marlin.ino.elf section `.text' will not fit in region `text'`

`ld.exe: region `text' overflowed by 10268 bytes`

`collect2.exe: error: ld returned 1 exit status`

Going back to bilinear leveling fixes this.

**Comment by oderwat** [comment]
I don't thinks that UBL fits into the Anet board ram without major cuttings of other features. You can start with leaving out SD Card stuff and may need to remove other features in the code manually.

**Comment by TheWalterWhite** [comment]
Disabling SD support has fixed the issue
