### ISSUE TITLE
FILAMENT_RUNOUT_SENSOR

### ISSUE THREAD

**Issue by extremeshok** [SkyNet3D/Marlin#14]
Could the empty middle pin of either S_X or S_Y connector be used for the  runout sensor on the Anet board ?

As per the code, what would  FIL_RUNOUT_PIN be ?

````
/**
 * Filament Runout Sensor
 * A mechanical or opto endstop is used to check for the presence of filament.
 *
 * RAMPS-based boards use SERVO3_PIN.
 * For other boards you may need to define FIL_RUNOUT_PIN.
 * By default the firmware assumes HIGH = has filament, LOW = ran out
 */
//#define FILAMENT_RUNOUT_SENSOR
#if ENABLED(FILAMENT_RUNOUT_SENSOR)
  #define FIL_RUNOUT_INVERTING false // set to true to invert the logic of the sensor.
  #define ENDSTOPPULLUP_FIL_RUNOUT // Uncomment to use internal pullup for filament runout pins if the sensor is defined.
  #define FILAMENT_RUNOUT_SCRIPT "M600"
#endif
````

**Comment by oderwat** [comment]
S_Y / S_X ? You mean the endswitch connectors? The middle pins are "+5V" for all of them. You can only use the same Pin as described for the Servo of the 3D-Touch / BLTouch... see here: https://www.thingiverse.com/thing:2091529

**Comment by G-Pereira** [comment]
Is it resolved? If so please close the issue, so people won't get confused
