### ISSUE TITLE
Anet A8 corrupted LCD intermittent 

### ISSUE THREAD

**Issue by kenthinson** [SkyNet3D/Marlin#21]
Hi I installed the SkyNet firmware Skynet V2.3.2 (fix 2) from Facebook. I get the following on my LCD screen sometimes. The printer continues to print correctly.
![img_0132](https://user-images.githubusercontent.com/2245494/27316545-699eb416-5535-11e7-894c-7dda8238064d.JPG)

**Comment by G-Pereira** [comment]
Why not try the latest release? ;)

**Comment by oderwat** [comment]
Thats a known problem. SkyNet3D also soon is to be integrated to Marlin directly, so you may open up a bug report later in their issue system.
